backend:
  name: github
  repo: ASmithStudent/SabineSmithPhotography # Path to your Github repository
  branch: master # Branch to update
  # media_folder: "../assets/img/uploads" # Media files will be stored in the repo under images/uploads
